# 🐼 محاضرة Pandas 
## من الصفر إلى تحليل البيانات

---

### 📚 ايه اللي هنتعلمه اليوم؟

| # | الموضوع |
|---|---|
| 1 | ما هي Pandas ولماذا نستخدمها؟ |
| 2 | Series – العمود الواحد |
| 3 | DataFrame – الجدول |
| 4 | قراءة البيانات (CSV) |
| 5 | استكشاف البيانات |
| 6 | اختيار وتصفية البيانات |
| 7 | التعامل مع القيم الناقصة |
| 8 | إضافة وحذف أعمدة |
| 9 | التجميع والإحصاء (groupby) |
| 10 | Merging & Joining – دمج DataFrames |
| 11 | Capstone – تحليل بيانات حقيقي |

---
> **💡 ملاحظة:** تأكد إنك مثبّت Pandas قبل ما تبدأ:
> ```bash
>! pip install pandas
> ```

---
## 1️⃣ ما هي Pandas؟

**Pandas** هي مكتبة Python مخصصة لـ **تحليل البيانات ومعالجتها**.

فكّرها كـ **Excel** بس بقوة Python!

### لماذا Pandas؟
- تقدر تقرأ ملفات CSV, Excel, JSON وغيرها
- تنظّف البيانات وتعالج القيم الناقصة
- تحلّل وتستخرج إحصائيات بسهولة
- أساس لكل مشاريع Machine Learning

### العلاقة مع NumPy
```
NumPy  →  أرقام وعمليات رياضية (arrays)
Pandas →  جداول وبيانات حقيقية (DataFrames)
```

In [3]:
# أول خطوة دائماً: import
import pandas as pd
import numpy as np

print('✅ Pandas version:', pd.__version__)
print('✅ NumPy version:', np.__version__)

✅ Pandas version: 2.2.3
✅ NumPy version: 1.26.4

---
## 2️⃣ Series – العمود الواحد

**Series** = عمود واحد من البيانات، له **index** (رقم أو اسم لكل عنصر)

```
Index  |  Value
-------|-------
  0    |   85
  1    |   90
  2    |   78
```

In [125]:
# إنشاء Series من قائمة
grades = pd.Series([85, 90, 78, 92, 88])
print('📊 درجات الطلاب:')
print(grades)
print()
print('النوع:', type(grades))

📊 درجات الطلاب:
0    85
1    90
2    78
3    92
4    88
dtype: int64

النوع: <class 'pandas.core.series.Series'>

In [6]:
# Series بـ index مخصص (اسم بدل رقم)
grades = pd.Series(
    [85, 90, 78, 92, 88],
    index=['أحمد', 'سارة', 'محمد', 'ليلى', 'خالد']
)
print('📊 درجات الطلاب مع الأسماء:')
print(grades)

📊 درجات الطلاب مع الأسماء:
أحمد    85
سارة    90
محمد    78
ليلى    92
خالد    88
dtype: int64

In [7]:
# الوصول لعنصر معين
print('درجة سارة:', grades['سارة'])
print('درجة أحمد:', grades['أحمد'])

# إحصاءات سريعة
print()
print('📈 أعلى درجة:', grades.max())
print('📉 أدنى درجة:', grades.min())
print('📊 المتوسط:', grades.mean())

درجة سارة: 90
درجة أحمد: 85

📈 أعلى درجة: 92
📉 أدنى درجة: 78
📊 المتوسط: 86.6

In [8]:
# عمليات على Series (مثل NumPy)
print('🎯 من نجح (درجة > 80):')
print(grades[grades > 80])

🎯 من نجح (درجة > 80):
أحمد    85
سارة    90
ليلى    92
خالد    88
dtype: int64

---
## 3️⃣ DataFrame – الجدول

**DataFrame** = جدول كامل من الأعمدة والصفوف  
كل عمود هو Series، وكلهم يشتركون في نفس الـ index

```
   الاسم   | العمر | المدينة
-----------|-------|--------
   أحمد    |  25   | الرياض
   سارة    |  30   | جدة
   محمد    |  22   | الدمام
```

In [10]:
# إنشاء DataFrame من dictionary
data = {
    'الاسم':    ['أحمد', 'سارة', 'محمد', 'ليلى', 'خالد'],
    'العمر':    [25, 30, 22, 28, 35],
    'المدينة':  ['الرياض', 'جدة', 'الدمام', 'الرياض', 'جدة'],
    'الراتب':   [8000, 12000, 6500, 9500, 15000]
}

df = pd.DataFrame(data)
print(df)

  الاسم  العمر المدينة  الراتب
0  أحمد     25  الرياض    8000
1  سارة     30     جدة   12000
2  محمد     22  الدمام    6500
3  ليلى     28  الرياض    9500
4  خالد     35     جدة   15000

In [11]:
# معلومات أساسية عن الـ DataFrame
print('🔢 الشكل (صفوف × أعمدة):', df.shape)
print('📋 أسماء الأعمدة:', df.columns.tolist())
print('🔑 الـ index:', df.index.tolist())

🔢 الشكل (صفوف × أعمدة): (5, 4)
📋 أسماء الأعمدة: ['الاسم', 'العمر', 'المدينة', 'الراتب']
🔑 الـ index: [0, 1, 2, 3, 4]

---
## 4️⃣ قراءة البيانات من ملف CSV

في الواقع، البيانات تجيك من ملفات وليس كـ dictionary.  
سنستخدم `pd.read_csv()` لقراءة الملفات.

لأغراض المحاضرة، سنصنع بيانات وهمية تشبه الواقع:

In [132]:
import io

# بيانات موظفين وهمية (تشبه ملف CSV حقيقي)
csv_data = """employee_id,name,age,department,salary,years_experience
101,Ahmed Ali,28,Engineering,12000,4
102,Sara Hassan,32,Marketing,9500,7
103,Mohamed Khalid,25,Engineering,8500,2
104,Layla Omar,29,HR,7500,5
105,Khaled Ibrahim,35,Engineering,15000,10
106,Fatima Nour,27,Marketing,8000,3
107,Omar Saeed,31,HR,7000,6
108,Nora Ahmed,24,Engineering,8000,1
109,Youssef Taha,33,Marketing,11000,8
110,Aisha Malik,26,HR,7200,3
"""

# قراءة البيانات
employees = pd.read_csv(io.StringIO(csv_data))

# لو عندك ملف CSV حقيقي:
#employees = pd.read_csv('employees.csv')

print('✅ تم تحميل البيانات!')

employees

✅ تم تحميل البيانات!

   employee_id            name  age   department  salary  years_experience
0          101       Ahmed Ali   28  Engineering   12000                 4
1          102     Sara Hassan   32    Marketing    9500                 7
2          103  Mohamed Khalid   25  Engineering    8500                 2
3          104      Layla Omar   29           HR    7500                 5
4          105  Khaled Ibrahim   35  Engineering   15000                10
5          106     Fatima Nour   27    Marketing    8000                 3
6          107      Omar Saeed   31           HR    7000                 6
7          108      Nora Ahmed   24  Engineering    8000                 1
8          109    Youssef Taha   33    Marketing   11000                 8
9          110     Aisha Malik   26           HR    7200                 3

---
## 5️⃣ استكشاف البيانات

أول ما تحمّل أي dataset، لازم تستكشفه بهذه الأوامر:

In [140]:
# أول 5 صفوف
print('📋 أول 5 صفوف:')
employees.head().style.background_gradient(cmap='Reds')

📋 أول 5 صفوف:

In [142]:
# آخر 3 صفوف
print('📋 آخر 3 صفوف:')
employees.tail(10)

📋 آخر 3 صفوف:

   employee_id            name  age   department  salary  years_experience
0          101       Ahmed Ali   28  Engineering   12000                 4
1          102     Sara Hassan   32    Marketing    9500                 7
2          103  Mohamed Khalid   25  Engineering    8500                 2
3          104      Layla Omar   29           HR    7500                 5
4          105  Khaled Ibrahim   35  Engineering   15000                10
5          106     Fatima Nour   27    Marketing    8000                 3
6          107      Omar Saeed   31           HR    7000                 6
7          108      Nora Ahmed   24  Engineering    8000                 1
8          109    Youssef Taha   33    Marketing   11000                 8
9          110     Aisha Malik   26           HR    7200                 3

In [17]:
# معلومات عامة عن البيانات
print('ℹ️ معلومات البيانات:')
employees.info()

ℹ️ معلومات البيانات:
<class 'pandas.core.frame.DataFrame'>
RangeIndex: 10 entries, 0 to 9
Data columns (total 6 columns):
 #   Column            Non-Null Count  Dtype
---  ------            --------------  -----
 0   employee_id       10 non-null     int64
 1   name              10 non-null     object
 2   age               10 non-null     int64
 3   department        10 non-null     object
 4   salary            10 non-null     int64
 5   years_experience  10 non-null     int64
dtypes: int64(4), object(2)
memory usage: 612.0+ bytes

In [18]:
# إحصاءات الأعمدة الرقمية
print('📊 إحصاءات البيانات:')
employees.describe()

📊 إحصاءات البيانات:

       employee_id        age        salary  years_experience
count     10.00000  10.000000     10.000000          10.00000
mean     105.50000  29.000000   9370.000000           4.90000
std        3.02765   3.651484   2573.821197           2.84605
min      101.00000  24.000000   7000.000000           1.00000
25%      103.25000  26.250000   7625.000000           3.00000
50%      105.50000  28.500000   8250.000000           4.50000
75%      107.75000  31.750000  10625.000000           6.75000
max      110.00000  35.000000  15000.000000          10.00000

In [19]:
# شكل البيانات
rows, cols = employees.shape
print(f'📐 البيانات تحتوي على {rows} موظف و {cols} أعمدة')

📐 البيانات تحتوي على 10 موظف و 6 أعمدة

---
## 6️⃣ اختيار وتصفية البيانات

### 6.1 اختيار أعمدة

In [21]:
# اختيار عمود واحد → Series
print('💰 أعمدة الراتب:')
print(employees['salary'])

💰 أعمدة الراتب:
0    12000
1     9500
2     8500
3     7500
4    15000
5     8000
6     7000
7     8000
8    11000
9     7200
Name: salary, dtype: int64

In [22]:
# اختيار أكثر من عمود → DataFrame
print('👤 الأسماء والأقسام والرواتب:')
employees[['name', 'department', 'salary']]

👤 الأسماء والأقسام والرواتب:

             name   department  salary
0       Ahmed Ali  Engineering   12000
1     Sara Hassan    Marketing    9500
2  Mohamed Khalid  Engineering    8500
3      Layla Omar           HR    7500
4  Khaled Ibrahim  Engineering   15000
5     Fatima Nour    Marketing    8000
6      Omar Saeed           HR    7000
7      Nora Ahmed  Engineering    8000
8    Youssef Taha    Marketing   11000
9     Aisha Malik           HR    7200

### 6.2 اختيار صفوف بـ `.iloc` و `.loc`

| الأمر | الاستخدام |
|-------|----------|
| `iloc` | بالرقم (index number) |
| `loc`  | بالاسم أو شرط |

In [24]:
# iloc - بالرقم
print('📌 الصف الأول (index 0):')
print(employees.iloc[0])
print()
print('📌 أول 3 صفوف:')
print(employees.iloc[0:3])

📌 الصف الأول (index 0):
employee_id                 101
name                  Ahmed Ali
age                          28
department          Engineering
salary                    12000
years_experience              4
Name: 0, dtype: object

📌 أول 3 صفوف:
   employee_id            name  age   department  salary  years_experience
0          101       Ahmed Ali   28  Engineering   12000                 4
1          102     Sara Hassan   32    Marketing    9500                 7
2          103  Mohamed Khalid   25  Engineering    8500                 2

In [25]:
# loc - بشرط
print('📌 موظفو قسم Engineering:')
employees.loc[employees['department'] == 'Engineering']

📌 موظفو قسم Engineering:

   employee_id            name  age   department  salary  years_experience
0          101       Ahmed Ali   28  Engineering   12000                 4
2          103  Mohamed Khalid   25  Engineering    8500                 2
4          105  Khaled Ibrahim   35  Engineering   15000                10
7          108      Nora Ahmed   24  Engineering    8000                 1

### 6.3 تصفية البيانات بشروط

In [27]:
# موظفون راتبهم أكثر من 10,000
print('💰 موظفون راتبهم > 10,000:')
employees[employees['salary'] > 10000]

💰 موظفون راتبهم > 10,000:

   employee_id            name  age   department  salary  years_experience
0          101       Ahmed Ali   28  Engineering   12000                 4
4          105  Khaled Ibrahim   35  Engineering   15000                10
8          109    Youssef Taha   33    Marketing   11000                 8

In [28]:
# شرطان معاً: Engineering + خبرة أكثر من 3 سنوات
# &  تعني AND
# |  تعني OR

mask = (employees['department'] == 'Engineering') & (employees['years_experience'] > 3)
print('🔧 مهندسون خبرتهم > 3 سنوات:')
employees[mask]

🔧 مهندسون خبرتهم > 3 سنوات:

   employee_id            name  age   department  salary  years_experience
0          101       Ahmed Ali   28  Engineering   12000                 4
4          105  Khaled Ibrahim   35  Engineering   15000                10

In [29]:
# isin() - اختيار من قائمة
print('🏢 موظفو Engineering أو Marketing:')
employees[employees['department'].isin(['Engineering', 'Marketing'])]

🏢 موظفو Engineering أو Marketing:

   employee_id            name  age   department  salary  years_experience
0          101       Ahmed Ali   28  Engineering   12000                 4
1          102     Sara Hassan   32    Marketing    9500                 7
2          103  Mohamed Khalid   25  Engineering    8500                 2
4          105  Khaled Ibrahim   35  Engineering   15000                10
5          106     Fatima Nour   27    Marketing    8000                 3
7          108      Nora Ahmed   24  Engineering    8000                 1
8          109    Youssef Taha   33    Marketing   11000                 8

---
## 7️⃣ التعامل مع القيم الناقصة (Missing Values)

في البيانات الحقيقية، دائماً في قيم ناقصة تظهر كـ **NaN** (Not a Number).  
لازم تعرف كيف تتعامل معها!

In [147]:
# بيانات فيها قيم ناقصة
messy_data = {
    'name':       ['أحمد', 'سارة', 'محمد', 'ليلى', 'خالد'],
    'age':        [25, None, 22, 28, None],
    'salary':     [8000, 12000, None, 9500, 15000],
    'department': ['IT', 'HR', 'IT', None, 'Marketing']
}

df_messy = pd.DataFrame(messy_data).style.background_gradient(cmap='Reds')
print('❗ البيانات مع القيم الناقصة:')
df_messy

❗ البيانات مع القيم الناقصة:

In [32]:
# كشف القيم الناقصة
print('🔍 أين القيم الناقصة؟')
print(df_messy.isnull())
print()
print('📊 عدد القيم الناقصة في كل عمود:')
print(df_messy.isnull().sum())

🔍 أين القيم الناقصة؟
    name    age  salary  department
0  False  False   False       False
1  False   True   False       False
2  False  False    True       False
3  False  False   False        True
4  False   True   False       False

📊 عدد القيم الناقصة في كل عمود:
name          0
age           2
salary        1
department    1
dtype: int64

In [33]:
# الحل 1: حذف الصفوف الناقصة
df_dropped = df_messy.dropna()
print('🗑️ بعد حذف الصفوف الناقصة:')
print(df_dropped)

🗑️ بعد حذف الصفوف الناقصة:
   name   age  salary department
0  أحمد  25.0  8000.0         IT

In [34]:
# الحل 2: ملء القيم الناقصة
df_filled = df_messy.copy()

# ملء العمر بالمتوسط
df_filled['age'] = df_filled['age'].fillna(df_filled['age'].mean())

# ملء الراتب بالوسيط (median)
df_filled['salary'] = df_filled['salary'].fillna(df_filled['salary'].median())

# ملء القسم بـ 'Unknown'
df_filled['department'] = df_filled['department'].fillna('Unknown')

print('✅ بعد ملء القيم الناقصة:')
df_filled

✅ بعد ملء القيم الناقصة:

   name   age   salary department
0  أحمد  25.0   8000.0         IT
1  سارة  25.0  12000.0         HR
2  محمد  22.0  10750.0         IT
3  ليلى  28.0   9500.0    Unknown
4  خالد  25.0  15000.0  Marketing

---
## 8️⃣ إضافة وحذف الأعمدة

In [36]:
# نسخة من البيانات للعمل عليها
df_work = employees.copy()

# إضافة عمود جديد: المكافأة (10% من الراتب)
df_work['bonus'] = df_work['salary'] * 0.10

# إضافة عمود: الراتب الإجمالي
df_work['total_salary'] = df_work['salary'] + df_work['bonus']

print('💰 بعد إضافة المكافأة:')
df_work[['name', 'salary', 'bonus', 'total_salary']]

💰 بعد إضافة المكافأة:

             name  salary   bonus  total_salary
0       Ahmed Ali   12000  1200.0       13200.0
1     Sara Hassan    9500   950.0       10450.0
2  Mohamed Khalid    8500   850.0        9350.0
3      Layla Omar    7500   750.0        8250.0
4  Khaled Ibrahim   15000  1500.0       16500.0
5     Fatima Nour    8000   800.0        8800.0
6      Omar Saeed    7000   700.0        7700.0
7      Nora Ahmed    8000   800.0        8800.0
8    Youssef Taha   11000  1100.0       12100.0
9     Aisha Malik    7200   720.0        7920.0

In [37]:
# إضافة عمود بشرط: Senior أو Junior
df_work['level'] = df_work['years_experience'].apply(
    lambda x: 'Senior' if x >= 5 else 'Junior'
)

print('🏅 مستوى كل موظف:')
df_work[['name', 'years_experience', 'level']]

🏅 مستوى كل موظف:

             name  years_experience   level
0       Ahmed Ali                 4  Junior
1     Sara Hassan                 7  Senior
2  Mohamed Khalid                 2  Junior
3      Layla Omar                 5  Senior
4  Khaled Ibrahim                10  Senior
5     Fatima Nour                 3  Junior
6      Omar Saeed                 6  Senior
7      Nora Ahmed                 1  Junior
8    Youssef Taha                 8  Senior
9     Aisha Malik                 3  Junior

In [38]:
# حذف عمود
df_work_clean = df_work.drop(columns=['bonus'])
print('🗑️ بعد حذف عمود bonus:')
print(df_work_clean.columns.tolist())

🗑️ بعد حذف عمود bonus:
['employee_id', 'name', 'age', 'department', 'salary', 'years_experience', 'total_salary', 'level']

In [39]:
# تغيير اسم عمود
df_renamed = employees.rename(columns={'salary': 'monthly_salary', 'name': 'full_name'})
print('✏️ بعد تغيير الأسماء:')
print(df_renamed.columns.tolist())

✏️ بعد تغيير الأسماء:
['employee_id', 'full_name', 'age', 'department', 'monthly_salary', 'years_experience']

---
## 9️⃣ التجميع والإحصاء – groupby()

**groupby** = تجميع البيانات حسب فئة وحساب إحصاءات لكل فئة  
مثل: "ما متوسط الراتب في كل قسم؟"

In [41]:
# متوسط الراتب لكل قسم
avg_salary = employees.groupby('department')['salary'].mean()
print('💼 متوسط الراتب لكل قسم:')
print(avg_salary)

💼 متوسط الراتب لكل قسم:
department
Engineering    10875.000000
HR              7233.333333
Marketing       9500.000000
Name: salary, dtype: float64

In [42]:
# عدد الموظفين في كل قسم
dept_count = employees.groupby('department')['name'].count()
print('👥 عدد الموظفين في كل قسم:')
print(dept_count)

👥 عدد الموظفين في كل قسم:
department
Engineering    4
HR             3
Marketing      3
Name: name, dtype: int64

In [43]:
# إحصاءات متعددة دفعة وحدة
dept_stats = employees.groupby('department')['salary'].agg(['mean', 'min', 'max', 'count'])
dept_stats.columns = ['متوسط', 'أدنى', 'أعلى', 'عدد الموظفين']
print('📊 إحصاءات الرواتب لكل قسم:')
dept_stats

📊 إحصاءات الرواتب لكل قسم:

                    متوسط  أدنى   أعلى  عدد الموظفين
department
Engineering  10875.000000  8000  15000             4
HR            7233.333333  7000   7500             3
Marketing     9500.000000  8000  11000             3

In [44]:
# ترتيب البيانات
print('🏆 الموظفون مرتبون من الأعلى راتباً:')
employees.sort_values('salary', ascending=False)[['name', 'department', 'salary']]

🏆 الموظفون مرتبون من الأعلى راتباً:

             name   department  salary
4  Khaled Ibrahim  Engineering   15000
0       Ahmed Ali  Engineering   12000
8    Youssef Taha    Marketing   11000
1     Sara Hassan    Marketing    9500
2  Mohamed Khalid  Engineering    8500
5     Fatima Nour    Marketing    8000
7      Nora Ahmed  Engineering    8000
3      Layla Omar           HR    7500
9     Aisha Malik           HR    7200
6      Omar Saeed           HR    7000

---
## 🔟 Merging & Joining – دمج أكثر من DataFrame

في الواقع، البيانات مش دايماً في جدول واحد.  
مثلاً: بيانات الموظفين في جدول، وبيانات أقسامهم في جدول ثاني.

Pandas عندها طريقتين رئيسيتين للدمج:

| الأمر | الاستخدام |
|-------|----------|
| `pd.merge()` | دمج جدولين بناءً على عمود مشترك (مثل SQL JOIN) |
| `pd.concat()` | لصق جداول فوق بعض أو جنب بعض |

### أنواع الـ merge:
```
inner  →  الصفوف الموجودة في الجدولين معاً فقط
left   →  كل الجدول الأيسر + ما يقابله من الأيمن
right  →  كل الجدول الأيمن + ما يقابله من الأيسر
outer  →  كل الصفوف من الجدولين
```

In [46]:
# جدول 1: بيانات الموظفين
df_employees = pd.DataFrame({
    'employee_id': [101, 102, 103, 104, 105],
    'name':        ['Ahmed', 'Sara', 'Mohamed', 'Layla', 'Khaled'],
    'dept_id':     [1, 2, 1, 3, 1]
})

# جدول 2: بيانات الأقسام
df_departments = pd.DataFrame({
    'dept_id':   [1, 2, 3, 4],
    'dept_name': ['Engineering', 'Marketing', 'HR', 'Finance'],
    'location':  ['Riyadh', 'Jeddah', 'Riyadh', 'Dammam']
})

print('👤 جدول الموظفين:')
print(df_employees)
print()
print('🏢 جدول الأقسام:')
print(df_departments)

👤 جدول الموظفين:
   employee_id     name  dept_id
0          101    Ahmed        1
1          102     Sara        2
2          103  Mohamed        1
3          104    Layla        3
4          105   Khaled        1

🏢 جدول الأقسام:
   dept_id    dept_name location
0        1  Engineering   Riyadh
1        2    Marketing   Jeddah
2        3           HR   Riyadh
3        4      Finance   Dammam

In [47]:
# INNER JOIN – الموظفون مع أقسامهم (الأقسام الموجودة فقط)
df_inner = pd.merge(df_employees, df_departments, on='dept_id', how='inner')
print('🔗 INNER JOIN – الموظفون مع أقسامهم:')
df_inner

🔗 INNER JOIN – الموظفون مع أقسامهم:

   employee_id     name  dept_id    dept_name location
0          101    Ahmed        1  Engineering   Riyadh
1          102     Sara        2    Marketing   Jeddah
2          103  Mohamed        1  Engineering   Riyadh
3          104    Layla        3           HR   Riyadh
4          105   Khaled        1  Engineering   Riyadh

In [48]:
# LEFT JOIN – كل الموظفين حتى لو قسمهم مش موجود
df_emp_extra = pd.concat([
    df_employees,
    pd.DataFrame([{'employee_id': 106, 'name': 'Nora', 'dept_id': 99}])
], ignore_index=True)

df_left = pd.merge(df_emp_extra, df_departments, on='dept_id', how='left')
print('⬅️ LEFT JOIN – كل الموظفين (حتى لو قسمهم غير موجود):')
df_left

⬅️ LEFT JOIN – كل الموظفين (حتى لو قسمهم غير موجود):

   employee_id     name  dept_id    dept_name location
0          101    Ahmed        1  Engineering   Riyadh
1          102     Sara        2    Marketing   Jeddah
2          103  Mohamed        1  Engineering   Riyadh
3          104    Layla        3           HR   Riyadh
4          105   Khaled        1  Engineering   Riyadh
5          106     Nora       99          NaN      NaN

In [49]:
# OUTER JOIN – كل شيء من الجدولين
df_outer = pd.merge(df_emp_extra, df_departments, on='dept_id', how='outer')
print('🔄 OUTER JOIN – كل الموظفين وكل الأقسام:')
df_outer

🔄 OUTER JOIN – كل الموظفين وكل الأقسام:

   employee_id     name  dept_id    dept_name location
0        101.0    Ahmed        1  Engineering   Riyadh
1        103.0  Mohamed        1  Engineering   Riyadh
2        105.0   Khaled        1  Engineering   Riyadh
3        102.0     Sara        2    Marketing   Jeddah
4        104.0    Layla        3           HR   Riyadh
5          NaN      NaN        4      Finance   Dammam
6        106.0     Nora       99          NaN      NaN

In [50]:
# دمج بأعمدة مختلفة الأسماء
df_salaries = pd.DataFrame({
    'emp_id':  [101, 102, 103, 104, 105],
    'salary':  [12000, 9500, 8500, 7500, 15000]
})

df_merged = pd.merge(
    df_employees,
    df_salaries,
    left_on='employee_id',
    right_on='emp_id',
    how='inner'
)
print('💰 الموظفون مع رواتبهم (أعمدة مختلفة الأسماء):')
df_merged[['employee_id', 'name', 'dept_id', 'salary']]

💰 الموظفون مع رواتبهم (أعمدة مختلفة الأسماء):

   employee_id     name  dept_id  salary
0          101    Ahmed        1   12000
1          102     Sara        2    9500
2          103  Mohamed        1    8500
3          104    Layla        3    7500
4          105   Khaled        1   15000

In [51]:
# pd.concat() – لصق جداول فوق بعض
new_employees = pd.DataFrame({
    'employee_id': [111, 112],
    'name':        ['Tariq', 'Hana'],
    'dept_id':     [2, 3]
})

all_employees = pd.concat([df_employees, new_employees], ignore_index=True)
print(f'👥 كل الموظفين بعد الدمج ({len(all_employees)} موظف):')
all_employees

👥 كل الموظفين بعد الدمج (7 موظف):

   employee_id     name  dept_id
0          101    Ahmed        1
1          102     Sara        2
2          103  Mohamed        1
3          104    Layla        3
4          105   Khaled        1
5          111    Tariq        2
6          112     Hana        3

In [52]:
# concat جنب بعض (axis=1) – إضافة أعمدة
df_info = pd.DataFrame({'phone': ['055-1111', '055-2222', '055-3333', '055-4444', '055-5555']})
df_full = pd.concat([df_employees, df_info], axis=1)
print('📞 الموظفون مع أرقام هواتفهم:')
df_full

📞 الموظفون مع أرقام هواتفهم:

   employee_id     name  dept_id     phone
0          101    Ahmed        1  055-1111
1          102     Sara        2  055-2222
2          103  Mohamed        1  055-3333
3          104    Layla        3  055-4444
4          105   Khaled        1  055-5555

### 🧠 متى تستخدم أي أمر؟

```
pd.merge()  ←  عندك عمود مشترك بين جدولين (مثل ID)
pd.concat() ←  تريد تجميع صفوف أو أعمدة من جداول متشابهة
```

---
## 🎯 Capstone – تحليل بيانات متكامل

الآن نطبّق كل اللي تعلمناه على تحليل حقيقي!

**السيناريو:** عندنا بيانات مبيعات محل، ونريد:
1. تنظيف البيانات
2. إضافة أعمدة محسوبة
3. استخراج تقرير بالمبيعات لكل فئة

In [55]:
# بيانات المبيعات
sales_csv = """order_id,product,category,quantity,unit_price,discount
1,Laptop,Electronics,2,3500,0.10
2,T-Shirt,Clothing,5,120,0
3,Phone,Electronics,1,2200,0.05
4,Jeans,Clothing,3,250,0.15
5,Headphones,Electronics,4,350,0
6,Jacket,Clothing,2,450,0.10
7,Tablet,Electronics,1,1800,0
8,Shoes,Clothing,6,300,0.20
9,Smartwatch,Electronics,3,800,0.05
10,Dress,Clothing,4,200,0
"""

sales = pd.read_csv(io.StringIO(sales_csv))
print('🛒 بيانات المبيعات:')
sales

🛒 بيانات المبيعات:

   order_id     product     category  quantity  unit_price  discount
0         1      Laptop  Electronics         2        3500      0.10
1         2     T-Shirt     Clothing         5         120      0.00
2         3       Phone  Electronics         1        2200      0.05
3         4       Jeans     Clothing         3         250      0.15
4         5  Headphones  Electronics         4         350      0.00
5         6      Jacket     Clothing         2         450      0.10
6         7      Tablet  Electronics         1        1800      0.00
7         8       Shoes     Clothing         6         300      0.20
8         9  Smartwatch  Electronics         3         800      0.05
9        10       Dress     Clothing         4         200      0.00

In [56]:
# الخطوة 1: استكشاف البيانات
print('📐 الشكل:', sales.shape)
print('❓ قيم ناقصة:\n', sales.isnull().sum())

📐 الشكل: (10, 6)
❓ قيم ناقصة:
 order_id      0
product       0
category      0
quantity      0
unit_price    0
discount      0
dtype: int64

In [57]:
# الخطوة 2: إضافة أعمدة محسوبة
sales['revenue'] = sales['quantity'] * sales['unit_price']
sales['discount_amount'] = sales['revenue'] * sales['discount']
sales['net_revenue'] = sales['revenue'] - sales['discount_amount']

print('💰 بعد حساب الإيرادات:')
sales[['product', 'quantity', 'unit_price', 'revenue', 'discount_amount', 'net_revenue']]

💰 بعد حساب الإيرادات:

      product  quantity  unit_price  revenue  discount_amount  net_revenue
0      Laptop         2        3500     7000            700.0       6300.0
1     T-Shirt         5         120      600              0.0        600.0
2       Phone         1        2200     2200            110.0       2090.0
3       Jeans         3         250      750            112.5        637.5
4  Headphones         4         350     1400              0.0       1400.0
5      Jacket         2         450      900             90.0        810.0
6      Tablet         1        1800     1800              0.0       1800.0
7       Shoes         6         300     1800            360.0       1440.0
8  Smartwatch         3         800     2400            120.0       2280.0
9       Dress         4         200      800              0.0        800.0

In [58]:
# الخطوة 3: تقرير حسب الفئة
category_report = sales.groupby('category').agg(
    عدد_الطلبات=('order_id', 'count'),
    إجمالي_الكمية=('quantity', 'sum'),
    إجمالي_الإيراد=('net_revenue', 'sum'),
    متوسط_الإيراد=('net_revenue', 'mean')
).round(2)

print('📊 تقرير المبيعات حسب الفئة:')
category_report

📊 تقرير المبيعات حسب الفئة:

             عدد_الطلبات  إجمالي_الكمية  إجمالي_الإيراد  متوسط_الإيراد
category
Clothing               5             20          4287.5          857.5
Electronics            5             11         13870.0         2774.0

In [59]:
# الخطوة 4: أفضل 3 منتجات ربحاً
print('🏆 أفضل 3 منتجات من حيث الإيراد:')
sales.sort_values('net_revenue', ascending=False)[['product', 'category', 'net_revenue']].head(3)

🏆 أفضل 3 منتجات من حيث الإيراد:

      product     category  net_revenue
0      Laptop  Electronics       6300.0
8  Smartwatch  Electronics       2280.0
2       Phone  Electronics       2090.0

In [60]:
# الخطوة 5: ملخص نهائي
total_revenue = sales['net_revenue'].sum()
total_orders = len(sales)
avg_order = sales['net_revenue'].mean()

print('=' * 40)
print('         📋 ملخص الأداء التجاري')
print('=' * 40)
print(f'  إجمالي الطلبات:   {total_orders}')
print(f'  إجمالي الإيراد:   {total_revenue:,.0f} ريال')
print(f'  متوسط قيمة الطلب: {avg_order:,.0f} ريال')
print('=' * 40)

========================================
         📋 ملخص الأداء التجاري
========================================
  إجمالي الطلبات:   10
  إجمالي الإيراد:   18,158 ريال
  متوسط قيمة الطلب: 1,816 ريال
========================================

---
## 🎉 تهانينا! أنهيت محاضرة Pandas

### ✅ ما تعلمناه اليوم:

| الموضوع | الأوامر الرئيسية |
|---------|----------------|
| إنشاء البيانات | `pd.Series()`, `pd.DataFrame()` |
| قراءة الملفات | `pd.read_csv()` |
| الاستكشاف | `.head()`, `.info()`, `.describe()`, `.shape` |
| الاختيار | `df['col']`, `.iloc[]`, `.loc[]` |
| التصفية | `df[condition]`, `.isin()` |
| القيم الناقصة | `.isnull()`, `.dropna()`, `.fillna()` |
| الأعمدة | `.assign()`, `.drop()`, `.rename()`, `.apply()` |
| التجميع | `.groupby()`, `.agg()`, `.sort_values()` |
| دمج الجداول | `pd.merge()`, `pd.concat()` |

---